[package]
name = "Tetris"
version = "0.1.0"
authors = ["Jianqiang <haojian@pdx.edu>, Hanyang Xiao <xhanyang@pdx.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigo = "0.0.13"
console="0.7.7"
rand = "0.3.14"
